# Generated by Django 4.2.7 on 2025-06-06 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_coupon_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
    ]
