# Generated by Django 4.2.7 on 2025-06-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cartorder_cart_id_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='cart_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
