# Generated by Django 4.2.7 on 2025-06-22 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_alter_cartorder_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enroll_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
