# Generated by Django 4.2.7 on 2025-06-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_note_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_answer_message',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
